### ISSUE TITLE
.context being deprecated in jQuery 1.10

### ISSUE THREAD

**Issue by geckofu** [Verba/jquery-readyselector#1]
According to the [jQuery doc](http://api.jquery.com/context/), the `.context` property was deprecated in jQuery 1.10, and may be removed without notice in a future version.

  Is there any workaround for this ?

**Comment by ragalie** [comment]
I don't see anything obvious. Do you have any ideas?

**Comment by dantetwc** [comment]
This change makes the plugin no longer working

**Comment by shawnngtq** [comment]
Is there any workaround for jQuery v3? Thanks.

**Comment by niyando** [comment]
@shawnngtq the workaround is to not use context and rely on a length check to see if the element is present after the dom is ready. 

```js
$(document).ready(function(){
  var container = $('.action_name.controller_name');
  if(container.length == 0)return;
  console.log('write script here')
})
```
