### ISSUE TITLE
Any idea how to make this work with Turbolinks?

### ISSUE THREAD

**Issue by chintanparikh** [Verba/jquery-readyselector#5]
With Turbolinks, we now need to use `$(document).on('ready page:load')`. Any idea how to adapt this to work with Turbolinks?

**Comment by akatriel** [comment]
This overrides the JS .ready() method and prevents the entire js file from being loaded on every page. You can require jquery.turbolinks in application.js and then it should work (https://github.com/kossnocorp/jquery.turbolinks). I add `class="<%= controller_name %> <%= action_name %>"` to the body tag and with the above it works great.

**Comment by ragalie** [comment]
I agree with @akatriel that the best option here is probably to use jquery.turbolinks, which overloads `$.ready`.
